<?php
$order = $block->getOrder();
?>
<div class="checkout-success">
    <?php if ($order->getIncrementId()) : ?>
        <?php if ($block->getCustomerId()) { ?>

            <div style="color:orange; text-align:center; font-size: 25px;">Estamos processando o pagamento</div>

            <div style="color:blue; font-size: 20px;">Informações sobre o pagamento</div>
        <?php
            echo "<p>";
            echo 'Número da compra:: ' . $order->getIncrementId();
            echo "</p>";
        } else {
            echo "<p>";
            echo 'Sua compra # está: <span>%1</span>.', $order->getIncrementId();
            echo "</p>";
        }
        ?>
        <p><?php echo __('Iremos mandar um email com a confirmação da compra e detalhes do rastreamento.') ?></p>
    <?php endif; ?>
</div>
